run:
  timeout: 5m
  skip-dirs:
    - templates
    - vendor
  skip-files:
    - ".*\\.tmpl$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - varcheck
    - deadcode

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US

issues:
  exclude-dirs:
    - templates
  exclude-files:
    - ".*\\.tmpl$"