linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  staticcheck:
    checks: ["all", "-SA1019"] # Disable deprecated usage warnings
  gosec:
    excludes:
      - G204 # Allow subprocess execution in tests
      - G306 # Allow file permissions
      - G404 # Allow weak random in tests

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
  disable:
    - unused # Too noisy for test files
    - gosec  # Disabled for now due to many test-related issues

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - templates
    - vendor
  exclude-files:
    - ".*\\.tmpl$"
  exclude:
    - "SA1019.*deprecated"
    - "ineffectual assignment to err"
    - "Error return value.*is not checked"