linters-settings:
  gofmt:
    simplify: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G204 # Subprocess launched with potential tainted input
      - G306 # Expect WriteFile permissions to be 0600 or less
      - G404 # Use of weak random number generator

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec

run:
  timeout: 5m
  skip-dirs:
    - templates
    - vendor

issues:
  exclude-files:
    - ".*\\.tmpl$"
  exclude:
    - "SA1019.*deprecated"  # Allow deprecated usage for backward compatibility