openapi: 3.0.3
info:
  title: verify-zap API
  description: |
    verify-zap RESTful API built with Go and Gin framework.
    
    ## Authentication
    Authentication is not currently configured for this API.
    
    ## Error Handling
    The API uses standard HTTP status codes and returns errors in the following format:
    ```json
    {
      "error": "Error message",
      "code": "ERROR_CODE"
    }
    ```
  version: 1.0.0
  contact:
    name: 
  license:
    name: 

servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.verify-zap.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the service
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /ready:
    get:
      summary: Readiness check
      description: Returns whether the service is ready to accept requests
      tags:
        - Health
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:

  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "healthy"
        timestamp:
          type: string
          format: date-time
        version:
          type: string
          example: "1.0.0"
        checks:
          type: object
          additionalProperties:
            type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code

tags:
  - name: Health
    description: Health check endpoints