name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage", "priority/medium"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of go-starter are you running?
      placeholder: ex. v1.0.0
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: blueprint-type
    attributes:
      label: Blueprint Type
      description: Which blueprint were you trying to generate?
      options:
        - web-api-standard
        - web-api-clean
        - web-api-ddd
        - web-api-hexagonal
        - cli-simple
        - cli-standard
        - library-standard
        - lambda-standard
        - lambda-proxy
        - microservice-standard
        - grpc-gateway
        - event-driven
        - monolith
        - workspace
        - Not applicable
    validations:
      required: false
      
  - type: dropdown
    id: architecture
    attributes:
      label: Architecture Pattern
      description: Which architecture pattern were you using? (if applicable)
      options:
        - simple
        - standard
        - clean
        - ddd
        - hexagonal
        - Not applicable
    validations:
      required: false
      
  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which framework did you select? (if applicable)
      options:
        - gin
        - echo
        - fiber
        - chi
        - stdlib
        - cobra
        - Not applicable
    validations:
      required: false
      
  - type: dropdown
    id: logger
    attributes:
      label: Logger Type
      description: Which logger were you using? (if applicable)
      options:
        - slog (default)
        - zap
        - logrus
        - zerolog
        - Not applicable
    validations:
      required: false
      
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: cli-command
    attributes:
      label: CLI Command Used
      description: Please provide the exact go-starter command you ran (if applicable)
      placeholder: |
        go-starter new my-project --type=web-api --framework=gin --logger=slog --database-driver=postgres
      render: bash
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command 'go-starter new my-project --type=web-api --framework=gin'
        2. Select options: architecture=clean, database=postgres, auth=jwt
        3. Navigate to generated project directory
        4. Run 'go build ./...'
        5. See compilation error
    validations:
      required: true
      
  - type: textarea
    id: configuration-details
    attributes:
      label: Configuration Details
      description: Please provide all configuration options you selected during generation
      placeholder: |
        - Blueprint: web-api-standard
        - Architecture: clean
        - Framework: gin
        - Logger: slog
        - Database: postgres + gorm
        - Authentication: jwt
        - Go Version: 1.21
        - Module Path: github.com/myuser/myproject
      value: |
        - Blueprint: 
        - Architecture: 
        - Framework: 
        - Logger: 
        - Database: 
        - Authentication: 
        - Go Version: 
        - Module Path:
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true