blank_issues_enabled: false
contact_links:
  - name: 📚 Main Documentation
    url: https://github.com/francknouama/go-starter/blob/main/README.md
    about: Please check the main documentation first
  - name: 🧪 Enhanced ATDD Quick Reference
    url: https://github.com/francknouama/go-starter/blob/main/docs/ENHANCED_ATDD_QUICK_REFERENCE.md
    about: Quick reference for Enhanced ATDD Quality Testing system
  - name: 🔧 CI Integration Guide
    url: https://github.com/francknouama/go-starter/blob/main/docs/CI_INTEGRATION.md
    about: Comprehensive CI integration and performance guide
  - name: 🎯 Progressive Disclosure Guide
    url: https://github.com/francknouama/go-starter/blob/main/CLAUDE.md#progressive-disclosure-system-deep-dive
    about: Learn about the Progressive Disclosure system (basic/advanced modes)
  - name: 📋 Blueprint Selection Guide
    url: https://github.com/francknouama/go-starter/blob/main/CLAUDE.md#blueprint-selection-guide
    about: Help choosing the right blueprint for your project
  - name: 💬 Community Discussions
    url: https://github.com/francknouama/go-starter/discussions
    about: Ask questions and discuss ideas with the community