blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/francknouama/go-starter/blob/main/README.md
    about: Please check the documentation first
  - name: Discussions
    url: https://github.com/francknouama/go-starter/discussions
    about: Ask questions and discuss ideas with the community