name: Documentation Issue
description: Report issues with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage", "priority/low"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
        
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README
        - Template documentation
        - CLI usage guide
        - Code comments
        - API documentation
        - Quick reference
        - Getting started guide
        - FAQ
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: issue-category
    attributes:
      label: Issue Category
      description: What category does this documentation issue fall into?
      options:
        - Missing information
        - Incorrect information
        - Outdated information
        - Unclear/confusing
        - Grammar/spelling
        - Formatting issue
        - Missing examples
        - Broken links
        - Other
    validations:
      required: true
      
  - type: textarea
    id: current-documentation
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (paste relevant section or provide link)
      placeholder: Current documentation states...
      
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue with the current documentation
      placeholder: The problem with the current documentation is...
    validations:
      required: true
      
  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: The documentation should be updated to...
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true