name: Enhanced ATDD Issue
description: Report issues or request improvements for the Enhanced ATDD Quality Testing system
title: "[ATDD]: "
labels: ["enhanced-atdd", "testing", "quality", "needs-triage", "priority/medium"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🧪 Enhanced ATDD Quality Testing Issue
        
        Use this template for issues related to the Enhanced ATDD (Acceptance Test Driven Development) quality testing system, including BDD scenarios, performance optimizations, and quality validations.
        
  - type: dropdown
    id: atdd-component
    attributes:
      label: ATDD Component
      description: Which part of the Enhanced ATDD system is affected?
      options:
        - BDD Scenarios (Gherkin)
        - Test Steps Implementation
        - Quality Validation (compilation, imports, variables)
        - Performance Caching System
        - Parallel Test Execution
        - CI/CD Integration
        - Test Reporting
        - Blueprint Quality Analysis
        - Framework Isolation Testing
        - Configuration Consistency Testing
        - AST-based Code Analysis
        - Thread Safety (sync.RWMutex)
        - Project Generation Caching
        - Enhanced Steps (enhanced_steps_test.go)
        - All components
    validations:
      required: true
      
  - type: dropdown
    id: test-suite
    attributes:
      label: Test Suite Affected
      description: Which parallel test suite is affected? (if applicable)
      options:
        - compilation (Project compilation validation)
        - imports (Unused imports detection)
        - variables (Unused variables analysis)
        - configuration (Configuration consistency)
        - framework-isolation (Framework cross-contamination)
        - All suites
        - Not applicable
    validations:
      required: false
      
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of ATDD issue is this?
      options:
        - Test failure/flakiness
        - Performance degradation
        - Caching issue (hit/miss rates)
        - Thread safety concern
        - BDD scenario bug
        - Test step implementation bug
        - CI/CD pipeline issue
        - Quality validation false positive/negative
        - AST analysis issue
        - Blueprint validation issue
        - Test reporting issue
        - Enhancement request
        - Documentation issue
        - Other
    validations:
      required: true
      
  - type: textarea
    id: test-scenario
    attributes:
      label: Test Scenario Details
      description: |
        If this is related to a specific BDD scenario, please provide the scenario name and details
      placeholder: |
        Feature: Code Quality Validation
        Scenario: Generated project compiles successfully
        Given I have a web-api blueprint with gin framework
        When I generate the project
        Then the project should compile without errors
      render: gherkin
      
  - type: textarea
    id: blueprint-configuration
    attributes:
      label: Blueprint Configuration
      description: What blueprint configuration was being tested?
      placeholder: |
        - Blueprint: web-api-clean
        - Architecture: clean
        - Framework: gin
        - Logger: slog
        - Database: postgres + gorm
        - Authentication: jwt
        - Complexity: standard
      value: |
        - Blueprint: 
        - Architecture: 
        - Framework: 
        - Logger: 
        - Database: 
        - Authentication: 
        - Complexity:
        
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the ATDD issue you're experiencing
      placeholder: |
        When running the enhanced quality tests, the compilation suite fails for gin+postgres configurations with the following error...
    validations:
      required: true
      
  - type: textarea
    id: performance-metrics
    attributes:
      label: Performance Impact
      description: |
        If this is performance-related, please provide metrics
      placeholder: |
        - Test execution time: 45 seconds (expected: <15 seconds)
        - Cache hit rate: 23% (expected: >70%)
        - Parallel efficiency: 3/5 suites running
        - Memory usage: 2GB peak
      value: |
        - Test execution time: 
        - Cache hit rate: 
        - Parallel efficiency: 
        - Memory usage:
        
  - type: textarea
    id: test-output
    attributes:
      label: Test Output/Logs
      description: Please provide relevant test output, error messages, or log files
      render: shell
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this ATDD issue?
      placeholder: |
        1. Navigate to tests/acceptance/enhanced/quality/
        2. Run: go test -v . -timeout 15m -run "TestQualityFeatures.*compile.*successfully"
        3. Observe failure in gin+postgres configuration
        4. Check cache metrics show low hit rate
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should the Enhanced ATDD system do?
      placeholder: |
        - All quality tests should pass within 15 seconds
        - Cache hit rate should be >70% for repeated configurations
        - All 5 parallel suites should run concurrently
        - Generated projects should compile without errors
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What is the Enhanced ATDD system actually doing?
      placeholder: |
        - Compilation suite fails after 30 seconds
        - Cache hit rate is only 25%
        - Only 3/5 suites running in parallel
        - Generated gin+postgres projects have missing imports
        
  - type: dropdown
    id: ci-environment
    attributes:
      label: CI Environment
      description: Where is this issue occurring?
      options:
        - Local development
        - GitHub Actions CI
        - Both local and CI
        - Unknown
    validations:
      required: true
      
  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Please provide environment information
      placeholder: |
        - OS: macOS 14.0
        - Go Version: 1.21
        - go-starter Version: v1.0.0
        - Test Runner: go test / godog
        - CI Runner: ubuntu-latest
      value: |
        - OS: 
        - Go Version: 
        - go-starter Version: 
        - Test Runner: 
        - CI Runner:
        
  - type: checkboxes
    id: affected-features
    attributes:
      label: Affected Features
      description: Which Enhanced ATDD features are impacted?
      options:
        - label: Project generation caching (60% performance improvement)
        - label: Parallel test execution (5 concurrent suites)
        - label: Thread-safe operations (sync.RWMutex)
        - label: BDD scenario execution (Godog/Cucumber)
        - label: AST-based code analysis
        - label: Quality gate reporting
        - label: CI/CD integration
        - label: Blueprint validation system
        
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        If you have ideas for fixing this issue, please describe them
      placeholder: |
        - Improve cache key generation to include architecture pattern
        - Add retry mechanism for flaky compilation tests
        - Optimize AST parsing for better performance
        - Fix thread safety issue in cache access
        
  - type: checkboxes
    id: testing-commitment
    attributes:
      label: Testing & Quality Commitment
      description: For fixes/enhancements to the ATDD system
      options:
        - label: I understand this affects the core testing infrastructure
        - label: I will thoroughly test any changes to avoid breaking existing tests
        - label: I will ensure any fixes maintain the 60% performance improvement
        - label: I will validate that parallel execution continues to work properly
        - label: I commit to following TDD practices for any ATDD system changes
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our standards
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
          required: true
        - label: I understand the critical importance of the Enhanced ATDD system
          required: true