name: Progressive Disclosure Issue
description: Report issues with the Progressive Disclosure system (basic/advanced modes, complexity levels)
title: "[Progressive]: "
labels: ["progressive-disclosure", "cli", "ux", "needs-triage", "priority/medium"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🎯 Progressive Disclosure System Issue
        
        Use this template for issues related to the Progressive Disclosure system, including basic/advanced modes, complexity levels, help filtering, and the two-tier CLI approach.
        
  - type: dropdown
    id: disclosure-component
    attributes:
      label: Progressive Disclosure Component
      description: Which part of the Progressive Disclosure system is affected?
      options:
        - Basic vs Advanced Help System
        - Complexity Level System (simple/standard/advanced/expert)
        - Two-Tier CLI Approach (cli-simple vs cli-standard)
        - Smart Flag Filtering
        - Blueprint Selection Logic
        - Default Application System
        - Interactive Prompting Prevention
        - Context-Aware Help
        - Help Rendering & Styling
        - All components
    validations:
      required: true
      
  - type: dropdown
    id: disclosure-mode
    attributes:
      label: Disclosure Mode
      description: Which disclosure mode is affected?
      options:
        - Basic Mode (14 essential flags)
        - Advanced Mode (18+ flags)
        - Auto-detection from flags
        - Mode switching (--basic/--advanced)
        - Not applicable
    validations:
      required: false
      
  - type: dropdown
    id: complexity-level
    attributes:
      label: Complexity Level
      description: Which complexity level is affected? (if applicable)
      options:
        - simple (Beginner-friendly, 8 files for CLI)
        - standard (Production-ready, 29 files for CLI)
        - advanced (Enterprise patterns)
        - expert (Full-featured)
        - Complexity auto-detection
        - Not applicable
    validations:
      required: false
      
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of Progressive Disclosure issue is this?
      options:
        - Wrong flags shown in basic mode
        - Wrong flags hidden in advanced mode
        - Complexity level not working
        - Blueprint selection incorrect
        - Interactive prompts appearing when they shouldn't
        - Smart defaults not applied
        - Help formatting issue
        - CLI confusion (simple vs standard)
        - Flag duplication in help
        - Context detection failure
        - Performance issue with help rendering
        - Enhancement request
        - Documentation issue
        - Other
    validations:
      required: true
      
  - type: textarea
    id: cli-command
    attributes:
      label: CLI Command Used
      description: Please provide the exact command that demonstrates the issue
      placeholder: |
        go-starter new --help
        # OR
        go-starter new my-project --type=cli --complexity=simple --basic
      render: bash
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Progressive Disclosure Behavior
      description: What should the Progressive Disclosure system do?
      placeholder: |
        When running 'go-starter new --help':
        - Should show basic mode by default (14 essential flags)
        - Should include hint about --advanced option
        - Should NOT show database/auth flags
        - Should format help with proper styling
      value: |
        ## Expected Help Output
        
        
        ## Expected Blueprint Selection
        
        
        ## Expected Flag Filtering
        
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Progressive Disclosure Behavior
      description: What is the system actually doing?
      placeholder: |
        When running 'go-starter new --help':
        - Shows advanced mode flags (18+ flags)
        - Missing hint about mode switching
        - Shows database/auth flags to beginners
        - Help formatting is broken
      value: |
        ## Actual Help Output
        
        
        ## Actual Blueprint Selection
        
        
        ## Actual Flag Filtering
        
    validations:
      required: true
      
  - type: textarea
    id: help-output
    attributes:
      label: Help Output
      description: Please paste the actual help output you're seeing
      render: shell
      
  - type: textarea
    id: flag-analysis
    attributes:
      label: Flag Analysis
      description: |
        Analysis of which flags are shown/hidden incorrectly
      placeholder: |
        ## Flags That Should Be Hidden (Basic Mode)
        - --database-driver (advanced only)
        - --auth-type (advanced only)
        - --banner-style (advanced only)
        
        ## Flags That Should Be Shown (Basic Mode)
        - --type (essential)
        - --name (essential)
        - --framework (essential)
        
        ## Duplicated Flags
        - None expected
      value: |
        ## Incorrectly Hidden Flags
        - 
        
        ## Incorrectly Shown Flags
        - 
        
        ## Duplicated Flags
        - 
        
        ## Missing Essential Flags
        - 
        
  - type: textarea
    id: complexity-test
    attributes:
      label: Complexity Level Testing
      description: |
        If testing complexity levels, describe the results
      placeholder: |
        Command: go-starter new test --type=cli --complexity=simple
        Expected: Generate cli-simple blueprint (8 files)
        Actual: Generated cli-standard blueprint (29 files)
        
        Default application test:
        Expected: Framework=cobra, Logger=slog automatically set
        Actual: Interactive prompts appeared
      value: |
        ## Complexity Command Tested
        
        
        ## Expected Blueprint Selection
        
        
        ## Actual Blueprint Selection
        
        
        ## Default Application Results
        
        
  - type: textarea
    id: user-experience
    attributes:
      label: User Experience Impact
      description: How does this affect the user experience?
      placeholder: |
        - Beginners are overwhelmed by too many options
        - Expert users can't find advanced options
        - Confusion between simple and standard CLI
        - Help is not context-aware
        - No clear progression path
      value: |
        ## Beginner Impact
        - 
        
        ## Expert User Impact
        - 
        
        ## CLI Confusion
        - 
        
        ## Navigation Issues
        - 
        
  - type: dropdown
    id: user-level
    attributes:
      label: User Experience Level
      description: What user level is most affected by this issue?
      options:
        - Beginner (basic mode users)
        - Intermediate (standard complexity users)
        - Advanced (advanced mode users)
        - Expert (all options users)
        - All user levels
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this Progressive Disclosure issue?
      placeholder: |
        1. Run 'go-starter new --help'
        2. Observe flags shown (should be 14, actually shows 18+)
        3. Run 'go-starter new --basic --help' 
        4. Compare output (should be same as step 2)
        5. Note flag duplication or missing context hints
      value: |
        1. 
        2. 
        3. 
        4. 
        5.
    validations:
      required: true
      
  - type: textarea
    id: environment-details
    attributes:
      label: Environment Details
      description: Please provide environment information
      placeholder: |
        - OS: macOS 14.0
        - Terminal: iTerm2
        - go-starter Version: v1.0.0
        - Go Version: 1.21
        - Shell: zsh
      value: |
        - OS: 
        - Terminal: 
        - go-starter Version: 
        - Go Version: 
        - Shell:
        
  - type: checkboxes
    id: affected-features
    attributes:
      label: Affected Progressive Disclosure Features
      description: Which features are impacted?
      options:
        - label: Basic mode help (14 essential flags)
        - label: Advanced mode help (18+ flags)
        - label: Smart flag filtering
        - label: Context-aware help hints
        - label: Two-tier CLI system (simple vs standard)
        - label: Complexity-aware blueprint selection
        - label: Smart defaults application
        - label: Interactive prompt prevention
        - label: Flag duplication elimination
        - label: Help styling and formatting
        
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        If you have ideas for improving the Progressive Disclosure system
      placeholder: |
        - Fix flag categorization in cmd/new.go
        - Improve help function to better filter flags
        - Add missing context hints for mode switching
        - Fix blueprint selection logic for complexity levels
        - Improve default application for CLI blueprints
        
  - type: checkboxes
    id: ux-commitment
    attributes:
      label: User Experience Commitment
      description: For fixes/enhancements to Progressive Disclosure
      options:
        - label: I understand this affects the core user experience
        - label: I will test both beginner and expert user workflows
        - label: I will ensure the two-tier CLI approach remains clear
        - label: I will validate that progressive learning paths work properly
        - label: I commit to maintaining the "start simple, grow as needed" philosophy
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our standards
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
          required: true
        - label: I understand the importance of Progressive Disclosure for user experience
          required: true