name: Question/Help
description: Ask a question or request help with using go-starter
title: "[Question]: "
labels: ["question", "needs-triage", "priority/low"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please check:
        - [Documentation](https://github.com/francknouama/go-starter/blob/main/README.md)
        - [FAQ](https://github.com/francknouama/go-starter/blob/main/docs/FAQ.md)
        - [Existing discussions](https://github.com/francknouama/go-starter/discussions)
        
  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Installation/Setup
        - Template Usage
        - Configuration
        - CLI Commands
        - Generated Code
        - Best Practices
        - Integration
        - Troubleshooting
        - Other
    validations:
      required: true
      
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I'm trying to understand how to...
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (what you're trying to achieve, what you've tried, etc.)
      placeholder: I'm working on... and I need to...
      
  - type: textarea
    id: current-approach
    attributes:
      label: What You've Tried
      description: What have you already tried? Include any commands or configurations you've used.
      placeholder: I've tried...
      render: shell
      
  - type: input
    id: version
    attributes:
      label: go-starter Version
      description: What version of go-starter are you using?
      placeholder: ex. v1.0.0
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true