name: Template Issue
description: Report issues with specific templates or request template improvements
title: "[Template]: "
labels: ["template", "needs-triage", "priority/high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to report issues with specific project templates or request template improvements.
        
  - type: dropdown
    id: blueprint-name
    attributes:
      label: Blueprint Name
      description: Which blueprint is this issue about?
      options:
        - web-api-standard
        - web-api-clean
        - web-api-ddd
        - web-api-hexagonal
        - cli-simple
        - cli-standard
        - library-standard
        - lambda-standard
        - lambda-proxy
        - microservice-standard
        - grpc-gateway
        - event-driven
        - monolith
        - workspace
        - All blueprints
    validations:
      required: true
      
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of blueprint issue is this?
      options:
        - Generated code doesn't compile
        - Missing dependency in go.mod
        - Incorrect configuration
        - Template syntax error
        - Framework integration issue
        - Database/ORM integration issue
        - Authentication implementation issue
        - Logger integration issue
        - Architecture pattern issue
        - Missing feature
        - Poor code quality
        - Post-hook execution failure
        - Progressive disclosure issue
        - Blueprint validation issue
        - Documentation issue
        - Other
    validations:
      required: true
      
  - type: textarea
    id: cli-command
    attributes:
      label: CLI Command Used
      description: Please provide the exact go-starter command you ran
      placeholder: |
        go-starter new my-project --type=web-api --architecture=clean --framework=gin --logger=slog --database-driver=postgres --auth-type=jwt
      render: bash
      
  - type: textarea
    id: configuration
    attributes:
      label: Configuration Details
      description: What configuration options did you select when generating the project?
      placeholder: |
        - Blueprint: web-api-clean
        - Architecture: clean
        - Framework: gin
        - Logger: slog
        - Database Driver: postgres
        - Database ORM: gorm
        - Authentication: jwt
        - Go Version: 1.21
        - Module Path: github.com/myuser/myproject
        - Progressive Disclosure Mode: basic/advanced
      value: |
        - Blueprint: 
        - Architecture: 
        - Framework: 
        - Logger: 
        - Database Driver: 
        - Database ORM: 
        - Authentication: 
        - Go Version: 
        - Module Path: 
        - Progressive Disclosure Mode:
    validations:
      required: true
      
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue with the template
      placeholder: When generating with these options, the following problem occurs...
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should the template generate instead?
      placeholder: The template should generate...
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What does the template actually generate?
      placeholder: Instead, the template generates...
      
  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If there are compilation errors or runtime errors, please paste them here
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true