name: Template Issue
description: Report issues with specific templates or request template improvements
title: "[Template]: "
labels: ["template", "needs-triage", "priority/high"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to report issues with specific project templates or request template improvements.
        
  - type: dropdown
    id: template-name
    attributes:
      label: Template Name
      description: Which template is this issue about?
      options:
        - web-api-standard
        - cli-standard
        - library-standard
        - lambda-standard
        - All templates
    validations:
      required: true
      
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of template issue is this?
      options:
        - Generated code doesn't compile
        - Missing dependency
        - Incorrect configuration
        - Template syntax error
        - Missing feature
        - Poor code quality
        - Documentation issue
        - Other
    validations:
      required: true
      
  - type: textarea
    id: configuration
    attributes:
      label: Configuration Used
      description: What configuration options did you select when generating the project?
      placeholder: |
        - Architecture: standard
        - Framework: gin
        - Logger: slog
        - Database: postgres
        - etc.
    validations:
      required: true
      
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the issue with the template
      placeholder: When generating with these options, the following problem occurs...
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should the template generate instead?
      placeholder: The template should generate...
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What does the template actually generate?
      placeholder: Instead, the template generates...
      
  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If there are compilation errors or runtime errors, please paste them here
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/francknouama/go-starter/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true