# Template Dependencies Configuration
# This file defines all dependencies used in the web-api-standard template

dependencies:
  # Web Framework Dependencies
  - module: "github.com/gin-gonic/gin"
    version: "v1.9.1"
    condition: "{{eq .Framework \"gin\"}}"
    
  - module: "github.com/labstack/echo/v4"
    version: "v4.11.3"
    condition: "{{eq .Framework \"echo\"}}"
    
  - module: "github.com/gofiber/fiber/v2"
    version: "v2.51.0"
    condition: "{{eq .Framework \"fiber\"}}"
    
  - module: "github.com/go-chi/chi/v5"
    version: "v5.0.10"
    condition: "{{eq .Framework \"chi\"}}"
  # No dependencies for stdlib framework

  # Common Dependencies
  - module: "github.com/spf13/viper"
    version: "v1.16.0"

  # Logger Dependencies
  - module: "go.uber.org/zap"
    version: "v1.26.0"
    condition: "{{eq .Logger \"zap\"}}"
    
  - module: "github.com/sirupsen/logrus"
    version: "v1.9.3"
    condition: "{{eq .Logger \"logrus\"}}"
    
  - module: "github.com/rs/zerolog"
    version: "v1.31.0"
    condition: "{{eq .Logger \"zerolog\"}}"

  # Database Driver Dependencies
  - module: "github.com/lib/pq"
    version: "v1.10.9"
    condition: "{{eq .DatabaseDriver \"postgres\"}}"

  # ORM Dependencies
  - module: "gorm.io/gorm"
    version: "v1.25.4"
    condition: "{{and (ne .DatabaseDriver \"\") (eq .DatabaseORM \"gorm\")}}"
    
  - module: "gorm.io/driver/postgres"
    version: "v1.5.2"
    condition: "{{and (eq .DatabaseDriver \"postgres\") (eq .DatabaseORM \"gorm\")}}"
    
  - module: "gorm.io/driver/mysql"
    version: "v1.5.2"
    condition: "{{and (eq .DatabaseDriver \"mysql\") (eq .DatabaseORM \"gorm\")}}"
    
  - module: "gorm.io/driver/sqlite"
    version: "v1.5.4"
    condition: "{{and (eq .DatabaseDriver \"sqlite\") (eq .DatabaseORM \"gorm\")}}"

  # Redis Dependencies
  - module: "github.com/redis/go-redis/v9"
    version: "v9.3.0"
    condition: "{{eq .DatabaseDriver \"redis\"}}"

  # Alternative Database Libraries
  - module: "github.com/jmoiron/sqlx"
    version: "v1.3.5"
    condition: "{{and (ne .DatabaseDriver \"\") (ne .DatabaseDriver \"redis\") (eq .DatabaseORM \"sqlx\")}}"
  # Note: sqlc is a code generation tool, not a runtime dependency
  # Users will need to install it separately: go install github.com/kyleconroy/sqlc/cmd/sqlc@latest

  # Authentication Dependencies
  - module: "github.com/golang-jwt/jwt/v5"
    version: "v5.0.0"
    condition: "{{eq .AuthType \"jwt\"}}"

  # Testing Dependencies
  - module: "github.com/stretchr/testify"
    version: "v1.8.4"