build:
	go build -o {{.ProjectName}} main.go

run:
	./{{.ProjectName}}

clean:
	rm -f {{.ProjectName}}

{{if eq .CommunicationProtocol "grpc"}}
proto:
	mkdir -p proto
	protoc --go_out=. --go-grpc_out=. proto/service.proto
{{end}}

.PHONY: build run clean {{if eq .CommunicationProtocol "grpc"}}proto{{end}}
