# Test configuration
environment: test

server:
  port: 8081
  read_timeout: 10
  write_timeout: 10
  idle_timeout: 30

logging:
  level: warn
  format: json

# Test-specific settings
test:
  cleanup_after_tests: true
  use_transactions: true
  parallel_execution: false