# Template Variables Configuration
# This file defines all variables used in the web-api-standard template

variables:
  - name: "ProjectName"
    description: "Name of the project"
    type: "string"
    required: true
    validation: "^[a-zA-Z0-9_-]+$"

  - name: "ModulePath"
    description: "Go module path"
    type: "string"
    required: true
    validation: "^[a-zA-Z0-9._/-]+$"

  - name: "Author"
    description: "Project author"
    type: "string"
    required: false
    default: ""

  - name: "Email"
    description: "Author email"
    type: "string"
    required: false
    default: ""

  - name: "License"
    description: "Project license"
    type: "string"
    required: false
    default: "MIT"
    choices:
      - "MIT"
      - "Apache-2.0"
      - "GPL-3.0"
      - "BSD-3-Clause"

  - name: "GoVersion"
    description: "Go version to use"
    type: "string"
    required: false
    default: "1.21"

  - name: "Framework"
    description: "Web framework"
    type: "string"
    required: false
    default: "gin"
    choices:
      - "gin"
      - "echo"
      - "fiber"
      - "chi"
      - "stdlib"

  - name: "Logger"
    description: "Logging library"
    type: "string"
    required: false
    default: "slog"
    choices:
      - "slog"
      - "zap"
      - "logrus"
      - "zerolog"

  - name: "DatabaseDriver"
    description: "Database driver"
    type: "string"
    required: false
    default: "postgres"
    choices:
      - ""
      - "postgres"
      - "mysql"
      - "sqlite"
      - "redis"

  - name: "DatabaseORM"
    description: "Database ORM/query builder (empty for standard library database/sql)"
    type: "string"
    required: false
    default: ""
    choices:
      - ""
      - "gorm"
      - "sqlx"
      - "sqlc"

  - name: "AuthType"
    description: "Authentication type"
    type: "string"
    required: false
    default: "jwt"
    choices:
      - ""
      - "jwt"
      - "oauth2"
      - "session"