name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ['1.22', '1.23', '1.24']
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    # Skip caching to avoid GitHub cache service issues

    - name: Download dependencies
      run: go mod download

    - name: Run tests and check coverage
      run: ./scripts/check_coverage.sh

    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.24'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        skip-cache: true

  template-validation:
    name: Template Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build go-starter
      run: make build

    - name: Run template compilation tests
      run: go test -v ./tests/integration/... -run TestTemplateCompilation
      timeout-minutes: 10

    - name: Run template logger tests
      run: go test -v ./tests/integration/... -run TestTemplateWithDifferentLoggers
      timeout-minutes: 10

    - name: Run template database tests  
      run: go test -v ./tests/integration/... -run TestTemplateWithDatabaseOptions
      timeout-minutes: 10

  acceptance-tests:
    name: ATDD Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build go-starter
      run: make build

    - name: Run ATDD tests for Web API blueprints
      run: go test -v ./tests/acceptance/... -timeout 20m
      timeout-minutes: 25

    - name: Upload ATDD test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: atdd-test-results
        path: |
          tests/acceptance/**/*_test.log
          tests/acceptance/**/*.out

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Build
      run: go build -o bin/go-starter .

    - name: Test CLI
      run: |
        chmod +x bin/go-starter || true
        ./bin/go-starter version
        ./bin/go-starter list
        ./bin/go-starter --help

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Download dependencies
      run: go mod download

    - name: Run benchmarks
      run: go test -bench=. -benchmem -cpuprofile=cpu.prof -memprofile=mem.prof ./tests/benchmarks/...

