FROM golang:{{.GoVersion}} AS builder

WORKDIR /app

COPY go.mod go.sum ./ 
RUN go mod download

COPY . .

RUN go build -o {{.ProjectName}} ./cmd/server

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/{{.ProjectName}} .

EXPOSE 8080

CMD ["./{{.ProjectName}}"]
