build:
	go build -o bin/{{.ProjectName}} ./cmd/server

run:
	./bin/{{.ProjectName}}

clean:
	rm -rf bin

lint:
	golangci-lint run

test:
	go test -v ./...

coverage:
	go test -v -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out

proto:
	protoc --go_out=. --go-grpc_out=. proto/service.proto

.PHONY: build run clean lint test coverage proto
